{% set name = "Flask-Excel" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b82ddfe6319ecf2f796ada9966737ac8eaf9a99d6bce773f8acdc08acd7e9fae

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - pyexcel-webio >=0.1.2
    - flask >=0.10.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - flask_excel

about:
  home: http://flask-excel.readthedocs.io/en/latest/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A flask extension using pyexcel to read, manipulate and write data in different excel formats: csv, ods, xls, xlsx and xlsm.
  description: |
    A flask extension that provides one application programming interface
    to read and write data in different excel file formats
  dev_url: https://github.com/pyexcel-webwares/Flask-Excel

extra:
  recipe-maintainers:
    - williamjamir
    - nicoddemus
